import type { Team } from './types';

export const PRELOADED_TEAMS: Team[] = [
  {
    id: 'thunder',
    name: 'Thunder Bolts',
    shortName: 'Bolts',
    colors: { primary: '#1a5276', secondary: '#f39c12', accent: '#ffffff' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'tb1', name: 'Alex Rodriguez', number: 12, position: 'P', battingAvg: 0.325, pitchingERA: 3.20, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#3a2010', eyeColor: '#4a2c0a', height: 'tall', build: 'average' } },
      { id: 'tb2', name: 'Ben Carter', number: 7, position: 'C', battingAvg: 0.280, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#8b4513', eyeColor: '#2266cc', height: 'average', build: 'stocky' } },
      { id: 'tb3', name: 'Chris Tanaka', number: 24, position: '1B', battingAvg: 0.350, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#553311', height: 'tall', build: 'stocky' } },
      { id: 'tb4', name: 'Danny Martinez', number: 5, position: '2B', battingAvg: 0.265, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#664422', height: 'short', build: 'average' } },
      { id: 'tb5', name: 'Eric Williams', number: 3, position: '3B', battingAvg: 0.310, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'average', build: 'average' } },
      { id: 'tb6', name: 'Frank O\'Brien', number: 10, position: 'SS', battingAvg: 0.295, pitchingERA: 9.99, throws: 'R', bats: 'L', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#337744', height: 'average', build: 'slim' } },
      { id: 'tb7', name: 'George Kim', number: 22, position: 'LF', battingAvg: 0.340, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#221100', height: 'average', build: 'slim' } },
      { id: 'tb8', name: 'Henry Davis', number: 8, position: 'CF', battingAvg: 0.275, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#4a2810', eyeColor: '#664422', height: 'short', build: 'average' } },
      { id: 'tb9', name: 'Isaac Johnson', number: 15, position: 'RF', battingAvg: 0.250, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#d4a060', eyeColor: '#2288bb', height: 'tall', build: 'average' } },
      { id: 'tb10', name: 'Jack Thompson', number: 27, position: 'DH', battingAvg: 0.305, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#4a2c0a', eyeColor: '#664422', height: 'average', build: 'stocky' } },
    ],
  },
  {
    id: 'eagles',
    name: 'Iron Eagles',
    shortName: 'Eagles',
    colors: { primary: '#2d5016', secondary: '#d4af37', accent: '#ffffff' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'ie1', name: 'Kevin Chang', number: 11, position: 'P', battingAvg: 0.290, pitchingERA: 2.85, throws: 'R', bats: 'R', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#221100', height: 'tall', build: 'average' } },
      { id: 'ie2', name: 'Liam Murphy', number: 9, position: 'C', battingAvg: 0.260, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f5d6b8', hairColor: '#8b4513', eyeColor: '#2266cc', height: 'average', build: 'stocky' } },
      { id: 'ie3', name: 'Marcus Brown', number: 33, position: '1B', battingAvg: 0.375, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'tall', build: 'stocky' } },
      { id: 'ie4', name: 'Nathan Patel', number: 4, position: '2B', battingAvg: 0.245, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#1a1a1a', eyeColor: '#442200', height: 'short', build: 'slim' } },
      { id: 'ie5', name: 'Oscar Garcia', number: 6, position: '3B', battingAvg: 0.320, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#664422', height: 'average', build: 'average' } },
      { id: 'ie6', name: 'Patrick Lee', number: 14, position: 'SS', battingAvg: 0.285, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#442200', height: 'average', build: 'average' } },
      { id: 'ie7', name: 'Quinn Anderson', number: 19, position: 'LF', battingAvg: 0.330, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#d4a060', eyeColor: '#2288bb', height: 'average', build: 'slim' } },
      { id: 'ie8', name: 'Ryan Thomas', number: 2, position: 'CF', battingAvg: 0.270, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#d4a574', hairColor: '#8b4513', eyeColor: '#664422', height: 'short', build: 'average' } },
      { id: 'ie9', name: 'Sam Wilson', number: 21, position: 'RF', battingAvg: 0.240, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#337744', height: 'tall', build: 'average' } },
      { id: 'ie10', name: 'Tommy Nguyen', number: 18, position: 'DH', battingAvg: 0.298, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#221100', height: 'average', build: 'stocky' } },
    ],
  },
  {
    id: 'sharks',
    name: 'Silver Sharks',
    shortName: 'Sharks',
    colors: { primary: '#1c2833', secondary: '#85c1e9', accent: '#f7f9f9' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'ss1', name: 'Andrew Foster', number: 17, position: 'P', battingAvg: 0.310, pitchingERA: 3.45, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'tall', build: 'average' } },
      { id: 'ss2', name: 'Brandon Cruz', number: 13, position: 'C', battingAvg: 0.255, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#664422', height: 'average', build: 'stocky' } },
      { id: 'ss3', name: 'Cody Reynolds', number: 44, position: '1B', battingAvg: 0.365, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#f5d6b8', hairColor: '#d4a060', eyeColor: '#2266cc', height: 'tall', build: 'stocky' } },
      { id: 'ss4', name: 'Derek Sullivan', number: 1, position: '2B', battingAvg: 0.238, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#8b4513', eyeColor: '#337744', height: 'short', build: 'slim' } },
      { id: 'ss5', name: 'Ethan Brooks', number: 23, position: '3B', battingAvg: 0.315, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#4a2c0a', eyeColor: '#2288bb', height: 'average', build: 'average' } },
      { id: 'ss6', name: 'Felix Torres', number: 16, position: 'SS', battingAvg: 0.290, pitchingERA: 9.99, throws: 'R', bats: 'L', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#664422', height: 'average', build: 'slim' } },
      { id: 'ss7', name: 'Gavin Scott', number: 28, position: 'LF', battingAvg: 0.345, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#2266cc', height: 'average', build: 'average' } },
      { id: 'ss8', name: 'Hunter Cole', number: 20, position: 'CF', battingAvg: 0.260, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#f0c8a0', hairColor: '#d4a060', eyeColor: '#553311', height: 'short', build: 'average' } },
      { id: 'ss9', name: 'Ian Mitchell', number: 25, position: 'RF', battingAvg: 0.230, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#3a2010', eyeColor: '#664422', height: 'tall', build: 'average' } },
      { id: 'ss10', name: 'Jake Peterson', number: 30, position: 'DH', battingAvg: 0.288, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'average', build: 'stocky' } },
    ],
  },
  {
    id: 'flames',
    name: 'Fire Flames',
    shortName: 'Flames',
    colors: { primary: '#c0392b', secondary: '#f39c12', accent: '#ffffff' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'ff1', name: 'Jaden King', number: 99, position: 'P', battingAvg: 0.300, pitchingERA: 3.10, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#c35817', eyeColor: '#664422', height: 'tall', build: 'average' } },
      { id: 'ff2', name: 'Kai Yamamoto', number: 8, position: 'C', battingAvg: 0.270, pitchingERA: 9.99, throws: 'R', bats: 'L', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#221100', height: 'average', build: 'stocky' } },
      { id: 'ff3', name: 'Leo Campbell', number: 34, position: '1B', battingAvg: 0.380, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#f5d6b8', hairColor: '#8b4513', eyeColor: '#2266cc', height: 'tall', build: 'stocky' } },
      { id: 'ff4', name: 'Mason Rivera', number: 2, position: '2B', battingAvg: 0.242, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#664422', height: 'short', build: 'slim' } },
      { id: 'ff5', name: 'Noah Bennett', number: 7, position: '3B', battingAvg: 0.318, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#d4a060', eyeColor: '#337744', height: 'average', build: 'average' } },
      { id: 'ff6', name: 'Oliver Hayes', number: 12, position: 'SS', battingAvg: 0.282, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#3a2010', eyeColor: '#2288bb', height: 'average', build: 'average' } },
      { id: 'ff7', name: 'Preston Ward', number: 22, position: 'LF', battingAvg: 0.338, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'average', build: 'slim' } },
      { id: 'ff8', name: 'Riley Cooper', number: 5, position: 'CF', battingAvg: 0.255, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#2266cc', height: 'short', build: 'average' } },
      { id: 'ff9', name: 'Sebastian Fox', number: 18, position: 'RF', battingAvg: 0.235, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#e8c898', hairColor: '#8b4513', eyeColor: '#664422', height: 'tall', build: 'average' } },
      { id: 'ff10', name: 'Tristan Cole', number: 29, position: 'DH', battingAvg: 0.310, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#4a2810', eyeColor: '#442200', height: 'average', build: 'stocky' } },
    ],
  },
  {
    id: 'storm',
    name: 'Desert Storm',
    shortName: 'Storm',
    colors: { primary: '#7d3c98', secondary: '#f0b27a', accent: '#ffffff' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'ds1', name: 'Ulysses Grant', number: 21, position: 'P', battingAvg: 0.295, pitchingERA: 3.55, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#4a2c0a', eyeColor: '#2266cc', height: 'tall', build: 'average' } },
      { id: 'ds2', name: 'Victor Diaz', number: 15, position: 'C', battingAvg: 0.265, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#1a1a1a', eyeColor: '#664422', height: 'average', build: 'stocky' } },
      { id: 'ds3', name: 'Wesley Ford', number: 42, position: '1B', battingAvg: 0.355, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'tall', build: 'stocky' } },
      { id: 'ds4', name: 'Xavier James', number: 3, position: '2B', battingAvg: 0.232, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#3a2010', eyeColor: '#2288bb', height: 'short', build: 'slim' } },
      { id: 'ds5', name: 'Yusuf Ali', number: 11, position: '3B', battingAvg: 0.325, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#c68642', hairColor: '#1a1a1a', eyeColor: '#442200', height: 'average', build: 'average' } },
      { id: 'ds6', name: 'Zachary Hart', number: 6, position: 'SS', battingAvg: 0.275, pitchingERA: 9.99, throws: 'R', bats: 'L', appearance: { skinColor: '#f5d6b8', hairColor: '#d4a060', eyeColor: '#337744', height: 'average', build: 'average' } },
      { id: 'ds7', name: 'Aaron Blake', number: 17, position: 'LF', battingAvg: 0.350, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#c35817', eyeColor: '#2266cc', height: 'average', build: 'slim' } },
      { id: 'ds8', name: 'Blake Curtis', number: 24, position: 'CF', battingAvg: 0.248, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'short', build: 'average' } },
      { id: 'ds9', name: 'Caleb Stone', number: 9, position: 'RF', battingAvg: 0.228, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#e8c898', hairColor: '#4a2810', eyeColor: '#664422', height: 'tall', build: 'average' } },
      { id: 'ds10', name: 'Damian Cross', number: 31, position: 'DH', battingAvg: 0.302, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#d4a574', hairColor: '#2a1508', eyeColor: '#442200', height: 'average', build: 'stocky' } },
    ],
  },
  {
    id: 'cyclones',
    name: 'Coastal Cyclones',
    shortName: 'Cyclones',
    colors: { primary: '#1a5276', secondary: '#48c9b0', accent: '#ffffff' },
    stadium: 'sunset',
    record: { wins: 0, losses: 0 },
    players: [
      { id: 'cc1', name: 'Edward Pierce', number: 14, position: 'P', battingAvg: 0.305, pitchingERA: 2.95, throws: 'R', bats: 'R', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#2266cc', height: 'tall', build: 'average' } },
      { id: 'cc2', name: 'Finn Gallagher', number: 10, position: 'C', battingAvg: 0.258, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#8b4513', eyeColor: '#337744', height: 'average', build: 'stocky' } },
      { id: 'cc3', name: 'Graham Norton', number: 36, position: '1B', battingAvg: 0.385, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#d4a574', hairColor: '#4a2c0a', eyeColor: '#2288bb', height: 'tall', build: 'stocky' } },
      { id: 'cc4', name: 'Harrison Fry', number: 4, position: '2B', battingAvg: 0.240, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#e8c898', hairColor: '#1a1a1a', eyeColor: '#664422', height: 'short', build: 'slim' } },
      { id: 'cc5', name: 'Isaiah Vance', number: 28, position: '3B', battingAvg: 0.330, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#553311', height: 'average', build: 'average' } },
      { id: 'cc6', name: 'Jasper Quinn', number: 19, position: 'SS', battingAvg: 0.278, pitchingERA: 9.99, throws: 'R', bats: 'L', appearance: { skinColor: '#c68642', hairColor: '#2a1508', eyeColor: '#442200', height: 'average', build: 'average' } },
      { id: 'cc7', name: 'Kieran Shaw', number: 23, position: 'LF', battingAvg: 0.342, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f0c8a0', hairColor: '#d4a060', eyeColor: '#2266cc', height: 'average', build: 'slim' } },
      { id: 'cc8', name: 'Landon Webb', number: 7, position: 'CF', battingAvg: 0.262, pitchingERA: 9.99, throws: 'L', bats: 'L', appearance: { skinColor: '#d4a574', hairColor: '#3a2010', eyeColor: '#664422', height: 'short', build: 'average' } },
      { id: 'cc9', name: 'Miles Jensen', number: 26, position: 'RF', battingAvg: 0.245, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#f5d6b8', hairColor: '#c35817', eyeColor: '#553311', height: 'tall', build: 'average' } },
      { id: 'cc10', name: 'Nolan Briggs', number: 33, position: 'DH', battingAvg: 0.295, pitchingERA: 9.99, throws: 'R', bats: 'R', appearance: { skinColor: '#8d5524', hairColor: '#0a0a0a', eyeColor: '#337744', height: 'average', build: 'stocky' } },
    ],
  },
];